name: Vigilant
options:
  bundleIdPrefix: io.vigilant.co
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"

settings:
  base:
    DEVELOPMENT_TEAM: 7AYMD222NU
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_EMIT_LOC_STRINGS: YES

targets:

  Vigilant:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - Shared
      - VigilantMac
    settings:
      base:
        PRODUCT_NAME: Vigilant
        PRODUCT_BUNDLE_IDENTIFIER: io.vigilant.co.Vigilant
        INFOPLIST_FILE: VigilantMac/Info.plist
        CODE_SIGN_ENTITLEMENTS: VigilantMac/Vigilant.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        INFOPLIST_KEY_CFBundleDisplayName: Vigilant
        MACOSX_DEPLOYMENT_TARGET: "14.0"

  VigilantRemote:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Shared
      - VigilantRemote
    settings:
      base:
        PRODUCT_NAME: Vigilant Remote
        PRODUCT_BUNDLE_IDENTIFIER: io.vigilant.co.VigilantRemote
        INFOPLIST_FILE: VigilantRemote/Info.plist
        CODE_SIGN_ENTITLEMENTS: VigilantRemote/VigilantRemote.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_CFBundleDisplayName: Vigilant
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDefault
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
